## GitHub Action main workflow
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
---
name: Go package
run-name: build by ${{ github.actor }}

#on: [push]
on:
  push:
#    branches: [main]
#  pull_request:
#    branches: [main]

  ## Allow manual workflow execution
  workflow_dispatch:

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        go-version: [ '1.20.x' ]

    steps:
      - name: Job URL
        run: echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        if: ${{ always() }}

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Ginkgo test framework
        run: |
          go get github.com/onsi/ginkgo/v2
          go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Build apps
        run: go build -v ./...

      - run: ls ${{ github.workspace }}

      - name: Go Test
        run: go test -v ./...

      #- name: Test with Go
      #  run: go test -json > TestResults-${{ matrix.go-version }}.json

      #- name: Upload Go test results
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: Go-results-${{ matrix.go-version }}
      #    path: TestResults-${{ matrix.go-version }}.json

      - name: Ginkgo Test
        run: ginkgo -vv ./...

      - name: Job status
        run: |
          echo "job.status: ${{ job.status }}"
        if: ${{ always() }}
